# Generated by Django 5.0 on 2023-12-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_user_userprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='user',
        ),
    ]
