# Generated by Django 5.0 on 2023-12-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_name_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
